import { ProfileLayout } from "@/components/layout/profile_layout/profileLayout";
import Head from "next/head";
import React from "react";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileLayout>
        <div>Profile</div>
      </ProfileLayout>
    </>
  );
}
