import Head from "next/head";
import { Navbar } from "@/components/shared/navbar/navbar";
import { GlobalLayout } from "@/components/layout/global_layout/globalLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>FreeBook</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* main content */}
      <main className="bg-white_gray-500 h-screen dark:bg-black-500 dark:text-white">
        <GlobalLayout />
      </main>
    </>
  );
}
